# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main","feature/action-build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore WebApplicationPipeline
    - name: Build
      run: dotnet build WebApplicationPipeline --no-restore
    - name: Test
      run: dotnet test WebApplicationPipeline --no-build --verbosity normal
    - name: Publish
      run: dotnet publish WebApplicationPipeline /p:configuration="Release"
