# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main","feature/action-build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3
    - name: Dir
      run: dir
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish WebApplicationPipeline/WebApplicationPipeline.csproj /p:configuration="Release"
