# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main","feature/action-build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: dev
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore WebApplicationPipeline
    - name: Build
      run: dotnet build WebApplicationPipeline --no-restore
    - name: Test
      run: dotnet test WebApplicationPipeline --no-build --verbosity normal
    - name: Publish
      run: dotnet publish WebApplicationPipeline/WebApplicationPipeline.csproj -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: WebSite
        path: website
        retention-days: 10
        
  deploy:
    runs-on: iis
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: WebSite
    - name: Stop IIS
      run: '%SYSTEMROOT%\System32\inetsrv\appcmd stop apppool /apppool.name:"Demo"'
    - name: Deploy
      run: xcopy /e /v /a /y *.* C:\inetpub\www\ThaiId
    - name: Start IIS
      run: iisreset /start
